<?php
// Variables
return [
  "creatorName" => "Prisha Software",
  "creatorUrl" => "/",
  "templateName" => "Admin",
  "templateSuffix" => "Admin Dashboard",
  "templateVersion" => "2.0.0",
  "templateFree" => true,
  "templateDescription" => "Property Dashboard",
  "templateKeyword" => "property",
  "licenseUrl" => "",
  "livePreview" => "",
  "productPage" => "",
  "support" => "",
  "adminTemplates" => "",
  "bootstrapDashboard" => "",
  "ogTitle" => "",
  "ogImage" => "",
  "ogType" => "product",
  "documentation" => "",
  "repository" => "",
  "gitRepo" => "",
  "gitRepoAccess" => "",
  "githubFreeUrl" => "https://github.com/githubFreeUrl",
  "facebookUrl" => "https://www.facebook.com/facebook/",
  "twitterUrl" => "https://x.com/x",
  "githubUrl" => "https://github.com/github",
  "dribbbleUrl" => "https://dribbble.com/dribbble",
  "instagramUrl" => "https://www.instagram.com/insta/"
];